GNU nano 2.5.3                                                                        File: /drone/docker-compose.yml

version: '3'
services:
  traefik:
    image: traefik:v2.1
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/traefik/traefik.yml:/etc/traefik/traefik.yml
      - /etc/traefik/acme/acme.json:/letsencrypt/acme.json
    labels:
      - traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=web
      - traefik.http.routers.http-catchall.middlewares=redirect-to-https@docker
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https

  village-valet:
    build: https://github.com/ItsAMeNick/village-valet.git
    container_name: village-valet
    restart: always
    labels:
      - traefik.http.routers.village-valet_dev.rule=Host(`example.com`,`www.example.com`)
      - traefik.http.routers.village-valet_dev.tls=true
      - traefik.http.routers.village-valet_dev.tls.certresolver=tls
    volumes:
      - /drone/village-valet/serviceAccountKey.json:/usr/src/app/keys/serviceAccountKey.json
    env_file: village-valet/.env

